import { Router } from 'express';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const router = Router();
const CAREER_OPS_PATH = process.env.CAREER_OPS_PATH || resolve(import.meta.dirname, '..', '..', '..');

function getProfilePath() {
  return resolve(CAREER_OPS_PATH, 'config', 'profile.yml');
}

function getCvPath() {
  return resolve(CAREER_OPS_PATH, 'cv.md');
}

// GET /api/profile — returns current profile + cv status
router.get('/', (req, res) => {
  const profilePath = getProfilePath();
  const cvPath = getCvPath();

  const result = {
    hasProfile: existsSync(profilePath),
    hasCv: existsSync(cvPath),
    profile: null,
    cvPreview: null,
  };

  if (result.hasProfile) {
    result.profile = readFileSync(profilePath, 'utf-8');
  }

  if (result.hasCv) {
    const cv = readFileSync(cvPath, 'utf-8');
    result.cvPreview = cv.substring(0, 500);
  }

  res.json(result);
});

// POST /api/profile — save profile.yml from form data
router.post('/', (req, res) => {
  const {
    full_name, email, phone, location, linkedin, portfolio_url, github,
    target_roles, archetypes,
    headline, exit_story, superpowers,
    target_range, currency, minimum, location_flexibility,
    country, city, timezone, visa_status,
  } = req.body;

  // Build YAML
  const yaml = [
    '# Career-Ops Profile Configuration',
    '# Generated by Career-Ops Web Dashboard',
    '',
    'candidate:',
    `  full_name: "${full_name || ''}"`,
    `  email: "${email || ''}"`,
    `  phone: "${phone || ''}"`,
    `  location: "${location || ''}"`,
    `  linkedin: "${linkedin || ''}"`,
    `  portfolio_url: "${portfolio_url || ''}"`,
    `  github: "${github || ''}"`,
    '',
    'target_roles:',
    '  primary:',
  ];

  // Target roles
  const roles = (target_roles || '').split(',').map(r => r.trim()).filter(Boolean);
  for (const role of roles) {
    yaml.push(`    - "${role}"`);
  }
  if (roles.length === 0) yaml.push('    - "Engineer"');

  // Archetypes
  yaml.push('  archetypes:');
  const archetypeList = (archetypes || '').split(',').map(a => a.trim()).filter(Boolean);
  for (const arch of archetypeList) {
    yaml.push(`    - name: "${arch}"`);
    yaml.push('      level: "Mid-Senior"');
    yaml.push('      fit: "primary"');
  }
  if (archetypeList.length === 0 && roles.length > 0) {
    yaml.push(`    - name: "${roles[0]}"`);
    yaml.push('      level: "Mid-Senior"');
    yaml.push('      fit: "primary"');
  }

  yaml.push('');
  yaml.push('narrative:');
  yaml.push(`  headline: "${headline || ''}"`);
  yaml.push(`  exit_story: "${exit_story || ''}"`);
  yaml.push('  superpowers:');
  const powers = (superpowers || '').split(',').map(s => s.trim()).filter(Boolean);
  for (const s of powers) {
    yaml.push(`    - "${s}"`);
  }

  yaml.push('');
  yaml.push('compensation:');
  yaml.push(`  target_range: "${target_range || ''}"`);
  yaml.push(`  currency: "${currency || 'USD'}"`);
  yaml.push(`  minimum: "${minimum || ''}"`);
  yaml.push(`  location_flexibility: "${location_flexibility || ''}"`);

  yaml.push('');
  yaml.push('location:');
  yaml.push(`  country: "${country || ''}"`);
  yaml.push(`  city: "${city || ''}"`);
  yaml.push(`  timezone: "${timezone || ''}"`);
  yaml.push(`  visa_status: "${visa_status || ''}"`);
  yaml.push('');

  const profilePath = getProfilePath();
  mkdirSync(dirname(profilePath), { recursive: true });
  writeFileSync(profilePath, yaml.join('\n'));
  res.json({ success: true, path: profilePath });
});

export default router;
